from path import Path

'''
Cleanup Mission Logic.  This code is intended to eliminate all the excess image files generated by the cameras.

** FILE NAME AND DIRECTORY NEEDS TO BE SPECIFIED!**
'''

''''
************************************************************************************************************************
Dictionary:
--Varibles--
d: The varible that recieves the directory of the folder
num_files: Calculates and holds the amount of file in the directory
************************************************************************************************************************
'''


d = Path('nombreDeLaLocalizacionDeLosFiles')
#Replace DIRECTORY with your required directory

num_files = len(d.files())

print(num_files)

#replace directory with your desired directory
for i in d.walk():
    if i.isfile():
        if i.name.startswith('file'):
            i.remove()

num_files = len(d.files())
print(num_files)


'''
VERSION CONTROL:
1- Juan G. Lastra Febles and Carlos Figueroa 10/05/2017 5:57 PM
Documented the code




Author : Esteban Lopez
'''